git-l10n/git-po

po/fr.po

l10n: fr.po v2.3.0 round 1

---

po/sv.po

l10n: sv.po: Update Swedish translation (2298t0f0u)

---

po/de.po

Please pull these updates of German translations for Git 2.3.0 (rnd1).
Thanks

German l10n updates for Git 2.3.0 (rnd1)

---

po/fr.po

Updated the 3 missing translations.

l10n: fr.po v2.3.0 round 2

---

po/de.po

Please pull German l10n updates for Git 2.3.0 (rnd2).
Thanks

German l10n updates for Git 2.3.0 (rnd2)

---

po/ca.po

Hopefully it's not too late to merge these.

Catalan translation updates for Git 2.3.0

---

po/de.po

Hi,
please pull this one fix in German translation for maint branch.
Thanks

one fix in German translation for maint branch

---

po/TEAMS
po/ru.po

I've completed Russian translation.

l10n: Added Russian translation. 100% complete.

---

po/sv.po

l10n: sv.po: Update Swedish translation (2305t0f0u)

---

po/fr.po

l10n: fr.po v2.4.0-rc0 round 1

---

po/ca.po

Signed-off-by: Alex Henrie <alexhenrie24@gmail.com>

l10n: ca.po: update translation

---

po/de.po

Please pull these updates in German translation for Git 2.4.0 (Rnd1).
Thanks

German l10n updates for Git 2.4.0 (Rnd1)

---

po/fr.po

l10n: fr.po v2.4.0 round 2

---

po/de.po

Please pull this update of German translation for Git 2.4.0-rc1.
Thanks

German l10n update for Git 2.4.0-rc1

---

po/de.po

Please pull these minor fixes for "maint" branch.
Thanks

Minor fixes for 'maint' branch

---

po/sv.po

l10n: sv.po: Update Swedish translation (2355t0f0u)

---

po/bg.po

l10n: Updated Bulgarian translation of git (2355t,0f,0u)

---

po/fr.po

Signed-off-by: Claude Dioudonnat <cdioudonnat@itnetwork.fr>

l10n: fr.po v2.5.0-rc0 (2355t)

---

po/de.po

Please pull German l10n updates for Git 2.5.0-rc0.
Thanks

German l10n updates for Git 2.5.0-rc0

---

po/ru.po

Signed-off-by: Dimitriy Ryazantcev <dimitriy.ryazantcev@gmail.com>

l10n: ru.po: update Russian translation

---

po/fr.po

l10n: fr v2.5.0 round 2 (2359t)

---

po/sv.po

l10n: sv.po: Update Swedish translation (2359t0f0u)

---

po/de.po

Please pull this update of German translation for Git 2.5.0 translation round 2.
Thanks

German l10n updates for Git 2.5.0 translation round 2

---

po/sv.po

l10n: sv.po: Update Swedish translation (2441t0f0u)

---

po/fr.po

l10n: fr.po v1.6.0 round 1 (2441t)

---

po/de.po

Please pull German l10n update for git v2.6.0 l10n rnd1.
Thanks

German l10n update for git v.2.6.0 l10n rnd1

---

po/fr.po

l10n: fr.po v2.6.0 round 2 (2440t)

---

po/de.po

Please pull German l10n update for git v2.6.0 l10n rnd2.
Thanks

German l10n update for git v2.6.0 l10n rnd2

---

po/fr.po

Signed-off-by: Élie Bouttier <elie@bouttier.eu>

l10n: fr.po: Fix typo

---

po/sv.po

l10n: sv.po: Update Swedish translation (2477t0f0u)

---

po/bg.po

l10n: Updated Bulgarian translation of git (2477t,0f,0u)

---

po/fr.po

l10n: fr v2.7.0 round 1 (2477t)

---

po/fr.po

l10n: fr.po v2.7.0 round 2 (2477t)

---

po/de.po

Please pull the German l10n updates for Git 2.7.
Thanks

German l10n updates for Git 2.7

---

po/TEAMS
po/ko.po

Signed-off-by: Changwoo Ryu <cwryu@debian.org>
Signed-off-by: Hyunjun Kim <yoloseem@users.noreply.github.com>

l10n: ko.po: Add Korean translation

---

po/ko.po

Signed-off-by: Changwoo Ryu <cwryu@debian.org>

l10n: ko.po: Update Korean translation

---

po/ko.po

Signed-off-by: Changwoo Ryu <cwryu@debian.org>
for 2.8.0 round 2

l10n: ko: Update Korean translation

---

po/fr.po

l10n: fr.po v2.8.0 round 2

---

po/sv.po

l10n: sv.po: Update Swedish translation (2530t0f0u)

---

po/fr.po

l10n: fr.po v2.8.0 round 3

---

po/de.po

Please pull German l10n updates for Git 2.8 l10n rnd 3.
Thanks

German l10n updates for Git 2.8 l10n rnd 3

---

po/pt_PT.po

Signed-off-by: Vasco Almeida <vascomalmeida@sapo.pt>

l10n: pt_PT: Update and add new translations

---

po/sv.po

l10n: sv.po: Update Swedish translation (2597t0f0u)

---

po/fr.po

l10n: fr.po v2.9.0rnd1

---

po/bg.po

l10n: Updated Bulgarian translation of git (2597t,0f,0u)

---

po/de.po

Please pull German l10n updates for Git 2.9.
Thanks

German l10n updates for Git 2.9

---

po/pt_PT.po

Update Portuguese translation for v2.10.0 round 1.

Update Portuguese translation

---

po/sv.po

l10n: sv.po: Update Swedish translation (2757t0f0u)

---

po/fr.po

l10n: fr.po v2.10.0-rc2

---

po/de.po

Please pull German l10n updates including both l10n rounds for Git 2.10 and one fix.
Thanks

German l10n updates

---

po/sv.po

l10n: sv.po: Update Swedish translation (2913t0f0u)

---

po/pt_PT.po

Signed-off-by: Vasco Almeida <vascomalmeida@sapo.pt>

l10n: pt_PT: update Portuguese translation

---

po/de.po

Please pull German l10n updates for Git 2.11.
Thanks

German l10n updates for Git 2.11

---

po/ca.po

Signed-off-by: Jordi Mas <jmas@softcatala.org>

l10n: fixes to Catalan translation

---

po/bg.po

l10n: bg:  Updated Bulgarian translation (2913t+0f+0u)

---

po/sv.po

l10n: sv.po: Update Swedish translation (3137t0f0u)

---

po/ca.po

Signed-off-by: Jordi Mas <jmas@softcatala.org>

l10n: update Catalan translation

---

po/fr.po

l10n: fr.po: v2.12.0 round 2 3139t

---

po/sv.po

l10n: sv.po: Update Swedish translation (3139t0f0u)

---

po/pt_PT.po

Signed-off-by: Vasco Almeida <vascomalmeida@sapo.pt>

l10n: pt_PT: update Portuguese tranlation

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3201t)

---

po/fr.po

l10n: fr.po v2.13 round 1

---

po/zh_CN.po

Translate 96 messages (3198t0f0u) for git v2.13.0-rc0.

l10n: zh_CN: for git v2.13.0 l10n round 1

---

po/de.po

Please pull German l10n updates for Git 2.13.
Thanks,
Ralf

German l10n update for Git 2.13

---

po/fr.po

l10n: fr.po v2.13 rnd 2

---

po/sv.po

l10n: sv.po: Update Swedish translation (3195t0f0u)

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3206t)

---

po/sv.po

l10n: sv.po: Update Swedish translation (3206t0f0u)

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3213t)

---

po/de.po

Please pull German translation update.
Thanks

German translation update

---

po/de.po

l10n: de.po: various fixes in German translation

---

po/es.po

Update es.po translation.
Thank you,

l10n: es.po: Update translation v2.15.0 round 1

---

po/sv.po

l10n: sv.po: Update Swedish translation (3245t0f0u)

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3245t)

---

po/es.po

Spanish translation for v2.15.0
Signed-off-by: Christopher Díaz Riveros <chrisadr@gentoo.org>

l10n: es.po: v2.15.0 round 2

---

po/ru.po

Signed-off-by: Dimitriy Ryazantcev <dimitriy.ryazantcev@gmail.com>

l10n: ru.po: update Russian translation v2.15.0-rc2

---

po/de.po
po/zh_CN.po

Translate 69 messages (3245t0f0u) for git v2.15.0-rc2.

l10n: zh_CN: for git v2.15.0 l10n round 2

---

po/de.po

Please pull German translation updates for Git 2.15.
Thanks

German translation updates for Git 2.15

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3284t)

---

po/es.po

Signed-off-by: Christopher Díaz Riveros <chrisadr@gentoo.org>

l10n: es.po: Update Spanish Translation v2.16.0

---

po/fr.po

l10n: fr.po 2.16 round 2

---

po/es.po

Signed-off-by: Christopher Díaz Riveros <chrisadr@gentoo.org>

l10n: es.po: Spanish translation 2.16.0 round 2

---

po/TEAMS
po/ru.po
po/sv.po
po/zh_CN.po

Translate 72 messages (3288t0f0u) for git v2.16.0-rc1.

l10n: zh_CN: for git v2.16.0 l10n round 2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3288t)

---

po/de.po

Please pull German l10n updates for Git 2.16.
Thanks

German l10n updates for Git 2.16

---

po/es.po

l10n: es.po: Update Spanish translation 2.17.0

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3376t)

---

po/fr.po

l10n: fr.po v2.17.0 round 1

---

po/fr.po

l10n: fr.po: v2.17.0 no fuzzy

---

po/de.po

Please pull German translation updates for Git 2.17.

German translation updates for Git 2.17

---

po/es.po

l10n: es.po: Spanish update for v2.18.0 round 1

---

po/fr.po

l10n: fr.po v2.18 round 1

---

po/es.po

l10n: es.po: Spanish update for v2.18.0 round 2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3608t)

---

po/es.po

l10n: es.po: Spanish update for v2.18.0 round 3

---

po/fr.po

l10n: fr.po v2.18.0 round 3

---

po/sv.po

l10n: sv.po: Update Swedish translation (3470t0f0u)

---

po/zh_CN.po

Reviewed-by: 依云 <lilydjwg@gmail.com>

l10n: zh_CN: review for git 2.18.0

---

po/de.po

Please pull German translation updates.
Thanks

German translation updates

---

po/es.po

l10n: es.po v2.19.0 round 2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (3958t)

---

po/zh_CN.po

Reviewed-by: 依云 <lilydjwg@gmail.com>

l10n: zh_CN: review for git v2.19.0 l10n

---

po/de.po

Please pull these updates to the German translation.

l10n: update German translation

---

po/fr.po

l10n: fr.po v2.20 rnd 1

---

po/sv.po

l10n: sv.po: Update Swedish translation (4185t0f0u)

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4185t)

---

po/es.po

l10n: es.po v2.20.0 round 3

---

po/fr.po

l10n: fr.po v2.20.0 round 3

---

po/sv.po

l10n: sv.po: Update Swedish translation (4187t0f0u)

---

po/bg.po

10n: bg.po: Updated Bulgarian translation (4187t)

---

po/zh_CN.po

Translate 257 new messages (4187t0f0u) for git 2.20.0.

l10n: zh_CN: for git v2.20.0 l10n round 1 to 3

---

po/de.po

Please pull these fixes to the German translation.
Thanks.

fixes to German translation

---

po/fr.po

Fr 2.21.0 rnd2

---

po/es.po

l10n: es: 2.21.0 round 2

---

po/bg.po

Signed-off-by: Nguyễn Thái Ngọc Duy <pclouds@gmail.com>
@jiangxin @alshopov

l10n: bg.po: correct typo

---

po/de.po

Please pull these updates to the German translation for Git 2.21.0.
Thanks!

German translation updates for Git 2.21.0

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4363t)

---

po/fr.po

l10n: fr.po v2.22.0.rnd1

---

po/es.po

l10n: es: 2.22.0 round 1

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4577t)

---

po/fr.po

l10n: fr.po v2.22.0 round 2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4580t)

---

po/es.po

l10n: es: 2.22.0 round 2

---

po/fr.po

l10n: fr v2.22.0 rnd 3

---

po/it.po

This PR updates the Italian translation for Git 2.22.
Note that not all strings are translated as I'm catching up with the backlog, I hope to have everything finished for Git 2.23/2.24.

l10n: it.po: Updated Italian translation

---

po/es.po

l10n: es: 2.22.0 round 3

---

po/TEAMS
po/zh_CN.po

Translate 273 new messages (4580t0f0u) for git 2.22.0.

l10n: zh_CN: for git v2.22.0 l10n round 1~3

---

po/TEAMS
po/de.po

This also changes the team leader for the german translations.

 l10n: de.po: Update German translation

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4581t)

---

po/fr.po

Signed-off-by: Cédric Malard <c.malard-git@valdun.net>

l10n: fr.po: Review French translation

---

po/it.po

This PR completes the Italian translation for Git.

l10n: it.po: update the Italian translation

---

po/de.po

Please pull these changes as proposed in pull request #380 which was sent to me as ruester#2

l10n: de.po: Fix typo in German translation

---

po/sv.po

l10n: sv.po: Update Swedish translation (4676t0f0u)

---

po/it.po

Update the Italian translation for Git v2.23.0 (l10n round 1), as well as adding some minor localization fixes.

l10n: it.po: update the Italian translation for v2.23.0

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4674t)

---

po/fr.po

l10n: fr v2.23.0 round 2

---

po/es.po

l10n: es: 2.23.0 round 2

---

po/it.po

This PR updates the Italian localization for Git v2.23.0, round 2.

l10n: it.po: update the Italian localization for v2.23.0 round 2

---

po/de.po

Signed-off-by: Matthias Rüster <matthias.ruester@gmail.com>
Reviewed-by: Ralf Thielow <ralf.thielow@gmail.com>
Reviewed-by: Phillip Szelat <phillip.szelat@gmail.com>

l10n: de.po: Update German translation

---

po/zh_CN.po

Translate 128 new messages (4674t0f0u) for git 2.23.0.

l10n: zh_CN: for git v2.23.0 l10n round 1~2

---

po/sv.po

l10n: sv.po: Update Swedish translation (4674t0f0u)

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4693)

---

po/fr.po

l10n: fr 2.24.0 rnd 1

---

po/it.po

This PR updates the Italian translation for Git 2.24.0.

it.po: update the Italian translation for Git 2.24.0

---

po/it.po

This PR updates the Italian translation for Git 2.24.0 (round number 2).

l10n: it.po: update the Italian translation for Git 2.24.0 round #2

---

po/fr.po

l10n: fr v2.24.0 rnd2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4694)

---

po/es.po

l10n: es: 2.24.0 round 2

---

po/sv.po

l10n: sv.po: Update Swedish translation (4695t0f0u)

---

po/zh_TW.po

Signed-off-by: pan93412 <pan93412@gmail.com>

l10n: zh_TW.po: update translation for v2.25.0 round 1

---

po/it.po

This PR updates the Italian translation for Git 2.25.0.

l10n: it.po: update the Italian translation for Git 2.25.0

---

po/fr.po

l10n: fr.po v2.25.0 rnd 1

---

po/sv.po

l10n: sv.po: Update Swedish translation (4800t0f0u)

---

po/es.po

l10n: es: 2.25.0 round #1

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4800t)

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4835t)

---

po/TEAMS
po/tr.po

This PR adds Turkish translations for Git.
Previous PR was too complicated to rebase, sorry about that. Please let me know if there's anything else.

l10n: tr: Add Turkish translations

---

po/fr.po

l10n: fr v2.26.0 rnd1

---

po/tr.po

l10n: tr: Add glossary for Turkish translations

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4839t)

---

po/fr.po

l10n: fr : v2.26.0 rnd 2

---

po/tr.po

l10n: tr: v2.26.0 round 2

---

po/es.po

l10n: es: 2.26.0 round#2

---

po/zh_TW.po

 l10n: zh_TW.po: v2.26.0 round 2 (0 untranslated)

---

po/tr.po

l10n: tr: Fix a couple of ambiguities

---

po/it.po

This PR updates the Italian translation for Git 2.27.0, round 1.

l10n: it.po: update the Italian translation for Git 2.27.0 round 1

---

po/sv.po

l10n: sv.po: Update Swedish translation (4839t0f0u)

---

po/tr.po

l10n: tr: v2.27.0 round 1

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4868t)

---

po/es.po

l10n: es: 2.27.0 round 1

---

po/zh_CN.po

Translate 72 new messages (4874t0f0u) for git 2.27.0.

l10n: zh_CN: for git v2.27.0 l10n round 1

---

po/sv.po

l10n: sv.po: Update Swedish translation (4875t0f0u)

---

po/tr.po

l10n: tr: v2.27.0 round 2

---

po/fr.po

l10n: fr.po v2.27.0 rnd 2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (4875t)

---

po/it.po

This PR updates the Italian translation for Git 2.27.0 round #2.

i18n: it.po: update the Italian translation for Git 2.27.0 round #2

---

po/zh_TW.po

l10n: zh_TW.po: v2.27.0 round 2 (0 untranslated)

---

po/it.po

This PR updates the Italian translation for Git 2.28.0.

l10n: it.po: update the Italian translation for Git 2.28.0 round 1

---

po/zh_TW.po

I'm not really sure what is the meaning of the remaining 2 strings, so I just leave them fuzzy.

l10n: zh_TW.po: v2.28.0 round 1 (2 untranslated)

---

po/zh_CN.po

Translate 70 new messages (4931t0f0u) for git 2.28.0.

l10n: zh_CN: for git v2.28.0 l10n round 1

---

po/es.po

l10n: es: 2.28.0 round 1

---

po/tr.po

Also includes general improvements to the existing strings.

l10n: tr: v2.29.0 round 1

---

po/fr.po

l10n: fr: v2.29.0 rnd 1

---

po/tr.po

l10n: tr: v2.29.0 round 2

---

po/fr.po

l10n: fr: v2.29.0 rnd 2

---

po/zh_TW.po

Some translations has been left it fuzzy since I don't know how to translate it perfect.

l10n: zh_TW.po: v2.29.0 round 2 (2 untranslated)

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5013t)

---

po/sv.po

l10n: sv.po: Update Swedish translation (5013t0f0u)

---

po/TEAMS
po/pt_PT.po

Update Portuguese Lead and official Repository.
`make` done at the top-level of this repository. Without any error.

l10n: pt_PT: update portugal's portuguese lead

---

po/sv.po

l10n: sv.po: Update Swedish translation (5038t0f0u)

---

po/tr.po

l10n: tr: v2.30.0-r1

---

po/sv.po

l10n: sv.po: Update Swedish translation (5037t0f0u)

---

po/tr.po

l10n: tr: v2.30.0-r2

---

po/fr.po

l10n: fr.po v2.30.0 rnd 2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5037t)

---

po/zh_TW.po

Signed-off-by: pan93412 <pan93412@gmail.com>
```
$ msgfmt -o /dev/null --stat po/zh_TW.po 
已翻譯 5036 條訊息，未翻譯 1 條訊息.
```

l10n: zh_TW.po: v2.30.0 round 2 (1 untranslated)

---

po/zh_CN.po

Translate 71 new messages (5037t0f0u) for git 2.30.0.

l10n: zh_CN: for git v2.30.0 l10n round 1 and 2

---

po/tr.po

l10n: tr: v2.31.0-rc1

---

po/fr.po

l10n: fr: v2.31.0 rnd 1

---

po/sv.po

l10n: sv.po: Update Swedish translation (5103t0f0u)

---

po/sv.po

l10n: sv.po: Update Swedish translation (5104t0f0u)

---

po/fr.po

l10n: fr: v2.31 rnd 2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5104t)

---

po/es.po

l10n: es: 2.31.0 round 2

---

po/pt_PT.po

* Newlines corrected.
* Add concept translation table
* Translated some.
* Corrected some.
Signed-off-by: Daniel Santos <hello@brighterdan.com>

l10n: pt_PT: add Portuguese translations part 1

---

po/TEAMS
po/id.po

This PR provides initial Indonesian translation (not completed yet)
Components translated:
* `init-db`
* `wt-status`
* `builtin/clone`
* `builtin/checkout`
* `builtin/fetch`
* Other core components:
* `builtin/remote`
* `builtin/index-pack`
* `push`
* `reset`
Note: Actually, there exists [WIP branch](https://github.com/git-l10n/git-po/tree/WIP/id%2Fanaufalm), but it seems stalled, so I have to restart from scratch.

l10n: Initial Indonesian translation

---

po/zh_TW.po

l10n: zh_TW.po: v2.31.0 round 2 (15 untranslated)

---

po/tr.po

l10n: tr: v2.32.0-r1

---

po/sv.po

l10n: sv.po: Update Swedish translation (5204t0f0u)

---

po/fr.po

Please not that while translating, I spotted a typo (missing space) in a string. So we may have to run a round 2

l10n: fr: v2.32.0 round 1

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5204t)

---

po/zh_TW.po

I'm still waiting for v2.32.0 round 2 so currently I prefer to leave it not merged until round 2 released and I completed translating round 2.

SEE README: l10n: zh_TW.po: v2.32.0 round 1 (11 untranslated)

---

po/pt_PT.po

* Eliminated 'Negation of emptiness' of 'nenhum' (not one/none)
* Eliminated 'Negation of emptiness' of 'nada' (nothing)
* Transformed 'Não' (No) into affirmative
* Some other translations
* Transforming 'não' (no) into affirmative
Signed-off-by: Daniel Santos <hello@brighterdan.com>

l10n: pt_PT: add Portuguese translations part 2

---

po/ru.po

Signed-off-by: Alexey Roslyakov <alexey.roslyakov@gmail.com>

l10n: ru.po: fix typo in Russian translation

---

po/zh_CN.po

l10n: zh_CN: for git v2.32.0 l10n round 1

---

po/es.po

l10n: es: 2.32.0 round 1

---

po/tr.po

l10n: tr: v2.33.0 round 1

---

po/id.po

* builtin/show-branch.c
* builtin/show-index.c
* builtin/show-ref.c
* builtin/shortlog.c
* builtin/describe.c
* bisect.c
* builtin/bisect--helper.c
* blame.c
* builtin/blame.c
* grep.c
* builtin/grep.c
* builtin/diff-tree.c
* builtin/diff.c
* help.c
Update translation for following components:
* diff.c

l10n: id: po-id for 2.33.0 (round 1)

---

po/de.po

Please pull the German l10n updates for Git 2.33.
(Matthias asked me to step in translating messages for this Git release.)
Thanks

German l10n updates for Git 2.33

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5227t)

---

po/sv.po

l10n: sv.po: Update Swedish translation (5227t0f0u)

---

po/id.po

Update translation for following component:
Translate following new component:
* builtin/revert.c

l10n: id: po-id for 2.33.0 round 2

---

po/fr.po

l10n: fr.po v2.33 rnd 2

---

po/de.po

Please pull German translation updates for Git v2.33.0 (Round 2).
Thanks

l10n: update German translation for Git v2.33.0 (rnd2)

---

po/zh_CN.po

- l10n: zh_CN: for git v2.33.0 l10n round 2
- l10n: README: refactor to use GFM syntax

l10n: zh_CN: for git v2.33.0 l10n round 2

---

po/tr.po

l10n: tr: v2.33 (round 2)

---

po/es.po

Signed-off-by: Alex Henrie <alexhenrie24@gmail.com>
Signed-off-by: Javier Spagnoletti phansys@gmail.com
Signed-off-by: Cleydyr Albuquerque <cleydyr@gmail.com>
Signed-off-by: Andrei Rybak <rybak.a.v@gmail.com>
Signed-off-by: Guillermo Ramos <gramosg>

l10n: es: 2.33.0 round 2

---

po/fr.po

l10n: fr v2.34.0 rnd1

---

po/zh_CN.po

l10n: zh-CN: v2.34.0 round 1

---

po/tr.po

l10n: tr: v2.34.0 round 2

---

po/zh_CN.po

l10n: zh_CN: 2.34.0 Round 2

---

po/sv.po

Updated to "untranslate" the trailers:key keyword.

l10n: sv.po: Update Swedish translation (5210t0f0u)

---

po/id.po

* gpg-interface.c
* send-pack.c
* fetch-pack.c
* upload-pack.c

l10n: po-id for 2.34 (round 2)

---

po/fr.po

l10n: fr: v2.34.0 round 2

---

po/zh_TW.po

Signed-off-by: pan93412 <pan93412@gmail.com>
Seems there are some issues in `git-po-helper`: https://github.com/git-l10n/git-po-helper/issues/7
Could you help me check that with `git-po-helper` again? Thanks!

l10n: zh_TW.po: v2.34.0 round 2 (0 untranslated)

---

po/pt_PT.po

* cleaning duplicate incorrect translations part 2
* update translation table
* unfuzzy some entries
* random line translations
Signed-off-by: Daniel Santos <hello@brighterdan.com>

l10n: pt_PT: cleaning duplicate translations (#2)

---

po/es.po

Signed-off-by: Omar Olivares <omar@olivares.cl>
Signed-off-by: Jaime Marquínez Ferrándiz <jaime.marquinez.ferrandiz@fastmail.net>
Signed-off-by: Alex Henrie <alexhenrie24@gmail.com>

l10n: es: 2.34.0 round 2

---

po/vi.po

Signed-off-by: Tran Ngoc Quan <vnwildman@gmail.com>

l10n: vi(5210t): Translation for v2.34.0 rd2

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5210t)

---

po/zh_CN.po

l10n: zh_CN: v2.34.0 round 3

---

po/tr.po

l10n: tr: v2.34.0 round 3

---

po/fr.po

l10n: fr: v2.34.0 rnd 3

---

po/zh_TW.po

Signed-off-by: Yi-Jyun Pan \<pan93412@gmail.com\>

l10n: zh_TW.po: v2.34.0 round 3 (0 untranslated)

---

po/vi.po

Signed-off-by: Tran Ngoc Quan <vnwildman@gmail.com>

l10n: vi(5211t): Translation for v2.34.0 rd3

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5211t)

---

po/id.po

- Translate following new components:
* merge.c
* rebase-interactive.c
* rebase.c
* midx.c
- Clean up obsolete translations

l10n: po-id for 2.34 (round 3)

---

po/tr.po

Minor error:
```po
#: branch.c:313
#, c-format
msgid "cannot force update the branch '%s'checked out at ‘%s’”
```
There is a space missing in source string.

l10n: tr: v2.35.0 round 1

---

po/id.po

* apply.c
* branch.c
* builtin/add.c
* builtin/am.c
* builtin/ls-files.c
* builtin/stash.c
* archive-tar.c
* archive-zip.c
Also clean up obsolete translations.

l10n: po-id for 2.35 (round 1)

---

po/fr.po

l10n: fr: v2.35.0 round 1

---

po/zh_CN.po

- Translate new messages
- Translate the word 'cone' instead of leaving it verbatim
(in the context of sparse checkout)
- Make translations of 'failed to' consistent
Reviewed-by: Teng Long <dyroneteng@gmail.com>
Reviewed-by: 依云 <lilydjwg@gmail.com>
Reviewed-by: Jiang Xin <worldhello.net@gmail.com>

l10n: zh_CN: v2.35.0 round 1

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5195t)

---

po/id.po

* advice.c
* alias.c
* sequencer.c
* sparse-index.c

l10n: po-id for 2.35 (round 2)

---

po/zh_TW.po

l10n: zh_TW: v2.35.0 round 2 (0 untranslated) 

---

po/tr.po

Also related: I've submitted translations for git-gui as well, around the time before 2.35, but it still haven't been reviewed. @jiangxin, would it be possible for you to have a look? Or should I ping again on the mailing list?

l10n: tr: v2.36.0 round 1

---

po/fr.po

l10n: fr: v2.36 round 1

---

po/tr.po

Signed-off-by: Emir SARI <emir_sari@icloud.com>

l10n: tr: v2.36.0 round 2

---

po/zh_TW.po

INFO [po/zh_TW.po@c9f01d5]      已翻譯 5282 條訊息.          
INFO checking commits: 1 passed.         

l10n: zh_TW: v2.36.0 round 1

---

po/fr.po

l10n: fr: v2.36 round 2

---

po/zh_CN.po

l10n: zh_CN v2.36.0 round 2

---

po/sv.po

l10n: sv.po: Update Swedish translation (5282t0f0u)

---

po/tr.po

Signed-off-by: Emir SARI <emir_sari@icloud.com>

l10n: tr: Update translations for v2.38.0 round #1

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5482t)

---

po/sv.po

l10n: sv.po: Update Swedish translation (5482t0f0u)

---

po/de.po

Hi,
please merge German translation updates for Git 2.38.
Thanks

German translation updates for Git 2.38

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5484t)

---

po/zh_CN.po

l10n: zh_CN v2.38.0 rounds 1 & 2

---

po/tr.po

Signed-off-by: Emir SARI <emir_sari@icloud.com>

l10n: tr: v2.38.0 round 2

---

po/es.po

Signed-off-by: Alex Henrie <alexhenrie24@gmail.com>

l10n: es: v2.38.0 round 3

---

po/zh_CN.po

l10n: zh_CN: 2.38.0 round 3

---

po/ca.po

Signed-off-by: Jordi Mas <jmas@softcatala.org>

l10n: Update Catalan translation - round 3

---

po/zh_TW.po

l10n: zh_TW.po: Git 2.38.0, round 3

---

po/fr.po

l10n: fr: v2.39 rnd 1

---

po/sv.po

l10n: sv.po: Update Swedish translation (5502t0f0)

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5501t)

---

po/zh_CN.po

l10n: zh_CN v2.39.0 round 1

---

po/tr.po

Did a merge by mistake. Reopening.

l10n: tr: v2.39.0 updates

---

po/zh_TW.po

l10n: zh_TW.po: Git 2.39-rc2

---

po/de.po

Please pull German translation update for Git 2.40.
Thanks

German translation update for Git 2.40

---

po/TEAMS

l10n: pt_PT: Change TEAMS file

---

po/fr.po

Fr 2.41.0 rnd1

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5515t)

---

po/de.po

Hi,
please pull German translation update for Git 2.41.
Thanks

German translation update for Git 2.41

---

po/TEAMS
po/zh_CN.po

l10n: zh_CN: Git 2.41.0 round #1

---

po/id.po

* advice.c
* archive.c
* attr.c
* config.c
* pack-revindex.c
* builtin/branch.c
* builtin/bundle.c
* builtin/pack-redundant.c
* builtin/rebase.c

l10n: po-id for 2.41 (round 1)

---

po/sv.po

l10n: sv.po: Update Swedish translation 5549t0f0u

---

po/zh_CN.po

l10n: zh_CN: 2.42.0 round #1

---

po/id.po

* commit-graph.c
* diff-no-index.c
* builtin/notes.c
* builtin/pack-refs.c
* builtin/worktree.c

l10n: po-id for 2.42 (round 1)

---

po/sv.po

l10n: sv.po: Update Swedish translation (5570t)

---

po/fr.po

l10n: fr: v2.43.0 rnd 1

---

po/tr.po

l10n: tr: v2.43.0, first round

---

po/uk.po

This PR adds 2.43 changes for uk.po file

l10n: update uk localization for v2.43

---

po/zh_TW.po

l10n: zh-TW: Git 2.43.0-rc1

---

po/zh_CN.po

l10n: zh_CN: for git 2.44 rnd1

---

po/fr.po

l10n: fr.po: v2.44.0 round 3

---

po/tr.po

l10n: tr: Update Turkish translations for 2.44

---

po/uk.po

Git 2.44 uk localization update

l10n: uk: v2.44 localization update

---

po/id.po

* builtin/replay.c
* commit-graph.c
* pack-bitmap.c
* sequencer.c

l10n: po-id for 2.44 (round 1)

---

po/de.po

Please pull German translation updates for Git 2.44.
Thanks

German translation updates for Git 2.44

---

po/id.po

* refs/reftable-backend.c
* branch.c
* builtin/column.c
* builtin/for-each-ref.c
* builtin/pack-refs.c
* revision.c

l10n: po-id for 2.45

---

po/de.po

Please pull German translation updates for Git 2.45.0.
Thanks.

German translation updates for Git 2.45.0

---

po/id.po

* builtin/for-each-repo.c
* builtin/refs.c
* commit-graph.c
* pack-bitmap-write.c
* pack-bitmap.c
* promisor-remote.c
* refs.c
* sequencer.c
* pseudo-merge.c
* refs/files-backend.c

l10n: po-id for 2.46

---

po/tr.po

l10n: tr: Update Turkish translations

---

po/vi.po

This also adds a terminology table for future translator's reference.

l10n: vi: Updated translation for 2.46

---

po/de.po

Please pull German translation update for Git 2.46.
Thanks

German translation update for Git 2.46

---

po/zh_TW.po

Merge once the final update period is reached by 2024-07-27.
For people prefers to check the diff details of this commit, check #781.
Last squashed at 5d0b1aecc6da92d6e26ea7f638f776fb880930a3 (location-less are applied).

l10n: zh_TW: Git 2.46

---

po/zh_TW.po

Co-authored-by: Lumynous <lumynou5.tw@gmail.com>

l10n: zh_TW: Git 2.47

---

po/ca.po

l10n: Update Catalan translation for Git 2.47

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5772t)

---

po/TEAMS

I have been working with @mlforcada  to take over the lead role for Catalan translation

l10n: new lead for Catalan translation

---

po/de.po

Hi,
please pull German translation updates for Git 2.47.
Thanks

German translations updates for git 2.47

---

po/zh_TW.po

> I will put the review to the translation PR later.

l10n: zh_TW: Git 2.48

---

po/tr.po

l10n: tr: Update Turkish translations for 2.48

---

po/id.po

* advice.c
* archive.c
* builtin/checkout.c
* builtin/describe.c
* builtin/gc.c
* builtin/index-pack.c
* builtin/notes.c
* builtin/pack-objects.c
* builtin/remote.c
* builtin/worktree.c
* commit.c
* fetch-pack.c
* hook.c
* object-name.c
* refs.c
* refs/files-backend.c
* remote.c
* worktree.c
* cache-tree.c
* daemon.c
* merge-ll.c

l10n: po-id for 2.48

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation for Git 2.48 (5804t)

---

po/zh_CN.po

l10n: zh_CN: updated translation for 2.48

---

po/de.po

Please pull German translation updates for Git 2.48.
Thanks

German translation updates for Git 2.48

---

po/fr.po

l10n: fr: 2.49 round 1

---

po/id.po

* builtin/cat-file.c
* builtin/fast-export.c
* builtin/fsck.c
* builtin/merge-tree.c
* builtin/mv.c
* builtin/reflog.c
* builtin/repack.c
* builtin/rev-list.c
* builtin/update-ref.c
* midx-write.c
* object-file.c
* parse-options.c
* promisor-remote.c
* refs/packed-backend.c
* scalar.c
* t/helper/test-pack-deltas.c
* git-send-email.perl
* builtin/diff-pairs.c

l10n: po-id for 2.50

---

po/vi.po

This includes the changes for Git 2.50 & 2.51, as I missed the merge window for 2.50.

l10n: Updated translation for vi-2.51

---

po/uk.po

l10n: uk: add 2.51 translation

l10n: uk: add 2.51 translation
