po/ca.po

This is actually a pretty serious problem because the "a" and "de" look like part of the commit hash.

l10n: ca.po: Fix trailing whitespace

---

po/fr.po

Fix simple typo in French translation.
Signed-off-by: Audric Schiltknecht <storm@chemicalstorm.org>

l10n: fr.po: Fix typo

---

po/fr.po

"tous le dépôts distants" -> "tous les dépôts distants"
Signed-off-by:	Antonin <antonin@delpeuch.eu>

l10n: fr.po Fixed grammar mistake

---

po/de.po

Der-, die- and dasselbe and their declensions are spelt as one word in German.
Signed-off-by: Robert Abel <rabel@robertabel.eu>
Signed-off-by: Ralf Thielow <ralf.thielow@gmail.com>

l10n: fixes to German translation

---

po/TEAMS

Add Gwan-gyeong Mun and Sihyeon Jang.
Signed-off-by: Changwoo Ryu <cwryu@debian.org>
Forgot to update the member list in the last PR.
Thanks.

l10n: TEAMS: Add ko team members

---

po/zh_CN.po

Translate 382 new messages (3958t0f0u) for git 2.19.0.

l10n: zh_CN: for git v2.19.0 l10n round 1 to 2

---

po/sv.po

Trying again, now the two commits are squashed together and rebased on top of the git-l10n master.

l10n: Update Swedish translation (4363t0f0u)

---

po/it.po

Remove an extra space between the dashes and the start of the "abort" option.
See #377

l10n: it.po: remove an extra space

---

po/it.po

This PR updates the Italian translation for Git 2.26.0, round 1.

l10n: it.po: update the Italian translation for Git 2.26.0 round 1

---

po/it.po

This PR updates the Italian translation for Git 2.26.0, round 2.

l10n: it.po: update the Italian translation for Git 2.26.0 round 2

---

po/it.po

This PR updates the Italian translation for Git 2.29.0, round 1.

l10n: it.po: update the Italian translation for Git 2.29.0 round 1

---

po/it.po

This PR updates the Italian translation for Git 2.29.0, round 2.

l10n: it.po: update the Italian translation for Git 2.29.0 round 2

---

po/id.po

Translate following components:
* builtin/add.c
* worktree.c
* builtin/branch.c
* builtin/merge.c
* builtin/rebase.c
* builtin/pull.c
* diff.c
* add-interactive.c
* builtin/log.c
* builtin/stash.c
* builtin/tag.c
* config.c
* reset.c
* builtin/remote.c
* builtin/rm.c
* builtin/mv.c
* builtin/clean.c
* builtin/help.c
* archive.c
* submodule.c
* submodule-config.c

l10n: id: po-id for 2.32.0 (round 1)

---

po/de.po
po/es.po
po/fr.po
po/it.po
po/ko.po
po/pt_PT.po
po/sv.po
po/tr.po
po/vi.po
po/zh_CN.po
po/zh_TW.po

Andrei pointed out a typo in the Swedish translation, where a config
variable name had been copied incorrectly.
By introducing typo detection function in "git-po-helper", more typos
were found. All easy-to-fix typos were fixed in this commit.
Reported-by: Andrei Rybak
Signed-off-by: Peter Krefting
Signed-off-by: Jiang Xin

l10n: fixed typos of mismatched constant strings

---

po/fr.po

Thank you for point out these errors. I installed git-po-helper, but was still using the old script in my workflow...

l10n: fr.po fix typos in commands and variables

---

po/id.po

Jiang Xin reported possible typos in po/id.po, all of them are mismatch
variable names. Fix them.
Reported-by: Jiang Xin <worldhello.net@gmail.com>

l10n: id: mismatch variable name fixes

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5230t)
Reduce warnings reported by git-po-helper to 23 which look like false
positives.  Since Bulgarian uses Cyrillic we mark substitutable parts
in capitals rather than quoting with <> which saves two chars per term
(2.5% real estate on a 80 char line) plus it is safer and simpler as
the <> chars have special (sometimes destructive) meaning for the
shells.  It is also easier for the user to parse.  See for example
the message:
git mailinfo [<options>] <msg> <patch> < mail >info
where both <> characters serve multiple functions.

l10n: bg.po: Updated Bulgarian translation (5230t)

---

po/sv.po

Fixes errors introduced in commit efedbb11de27a22cf9d4c75255057716f0b1b8ce
when running git-po-helper.

l10n: sv.po: Fix git-po-helper breakage

---

po/tr.po

l10n: tr: v2.34.0 round 1

---

po/id.po

* add-interactive.c
* add-patch.c
* diff.c
* gc.c
* builtin/bisect--helper.c
* builtin/merge.c
* builtin/rebase.c
* builtin/pull.c
* builtin/push.c
* apply.c
* bundle.c
* git.c
* git-send-email.perl
* rerere.c
* builtin/am.c
* builtin/apply.c
* builtin/archive.c
* builtin/bundle.c
* builtin/cat-file.c
* builtin/commit-tree.c
* builtin/count-objects.c
* builtin/difftool.c
* builtin/fast-export.c
* builtin/fast-import.c
* builtin/fetch-pack.c
* builtin/fsck.c
* builtin/gc.c
* builtin/hash-object.c
* builtin/ls-files.c
* builtin/ls-remote.c
* builtin/ls-tree.c
* builtin/read-tree.c
* builtin/receive-pack.c
* builtin/reflog.c
* builtin/repack.c
* …

l10n: po-id for 2.34 (round 1)

---

po/ca.po
po/ko.po

When checking typos in file "po/ko.po", "git-po-helper" reports lots of
false positives because there are no spaces between ASCII and Korean
characters. After applied commit adee197 "(dict: add smudge table for
Korean language, 2021-11-11)" [1] to suppress these false positives,
some easy-to-fix typos are found.
[1] https://github.com/git-l10n/git-po-helper/commit/adee19757cb

l10n: ko: fix typos found by git-po-helper

---

po/it.po

Fix typos found by git-po-helper.

l10n: it: fix typos found by git-po-helper

---

po/id.po

* add-interactive.c
* branch.c
* config.c
* help.c
* merge-ort-wrappers.c
* builtin/bisect--helper.c
* builtin/branch.c
* builtin/cat-file.c
* builtin/checkout.c
* builtin/reflog.c
* builtin/remote.c
* builtin/unpack-objects.c
* connect.c
* connected.c
* date.c
* hook.c
* files-backend.c
* ident.c
* merge-ort.c
* merge-recursive.c
* refs.c
* refspec.c
* revision.c
* symlinks.c
* worktree.c
* builtin/notes.c
* builtin/multi-pack-index.c
* builtin/merge-base.c

l10n: po-id for 2.36 (round 1)

---

po/id.po

* add-patch.c
* advice.c
* builtin/add.c
* builtin/am.c
* builtin/gc.c
* builtin/help.c
* builtin/ls-files.c
* builtin/merge.c
* diff.c
* merge-ort.c
* merge-tree.c
* object-file.c
* pack-bitmap.c
* remote.c
* revision.c
* setup.c
* builtin/bugreport.c
* builtin/checkout--worker.c
* builtin/checkout-index.c
* builtin/commit-graph.c
* builtin/fmt-merge-msg.c
* builtin/for-each-ref.c
* builtin/merge-file.c
* builtin/merge-recursive.c
* builtin/range-diff.c
* bundle-uri.c
* chunk-format.c
* color.c
* commit-graph.c
* delta-islands.c
* diagnose.c
* diff-lib.c
* diff-no-index.c
* diffcore-order.c
* diffcore-rename.c
* diffcore-rotate.c
* dir.c
* editor.c
* for-each-repo.c
* parse-options-cb.c
* …

l10n: po-id for 2.38 (round 1)

---

po/id.po

* branch.c
* builtin/log.c
* builtin/rebase.c
* builtin/remote.c
* builtin/reset.c
* builtin/rev-list.c
* builtin/rev-parse.c
* builtin/revert.c
* help.c
* merge.c
* builtin/check-attr.c
* builtin/check-ignore.c
* builtin/check-mailmap.c
* builtin/column.c
* builtin/credential-cache--daemon.c
* builtin/credential-cache.c
* builtin/credential-store.c
* builtin/diagnose.c
* builtin/env--helper.c
* builtin/fsmonitor--daemon.c
* builtin/interpret-trailers.c
* builtin/mailinfo.c
* builtin/mailsplit.c
* builtin/mktag.c
* builtin/mktree.c
* builtin/pack-redundant.c
* builtin/replace.c
* builtin/rerere.c
* builtin/stripspace.c
* bulk-checkin.c
* commit.c
* …

l10n: po-id for 2.38 (round 2)

---

po/id.po

* sequencer.c
* wt-status.c
* compat/compiler.h
* compat/disk.h
* compat/fsmonitor/fsm-health-win32.c
* compat/fsmonitor/fsm-listen-darwin.c
* compat/fsmonitor/fsm-listen-win32.c
* compat/fsmonitor/fsm-settings-win32.c
* compat/mingw.c
* compat/obstack.c
* compat/regex/regcomp.c
* compat/simple-ipc/ipc-unix-socket.c
* compat/simple-ipc/ipc-win32.c
* compat/terminal.c
* convert.c
* entry.c
* environment.c
* exec-cmd.c
* git-merge-octopus.sh
* git-sh-setup.sh
* list-objects-filter-options.c
* list-objects-filter-options.h
* list-objects.c
* lockfile.c
* ls-refs.c
* mailinfo.c
* name-hash.c
* notes-merge.c
* notes-utils.c
* pkt-line.c
* preload-index.c
* pretty.c
* promisor-remote.c
* protocol-caps.c
* read-cache.c
* scalar.c
* …

l10n: po-id for 2.38 (round 3)

---

po/id.po

All of updates are new strings translation.
* builtin/bundle.c
* builtin/describe.c
* builtin/diff.c
* builtin/fsck.c
* builtin/gc.c
* builtin/merge-tree.c
* builtin/repack.c
* builtin/revert.c
* builtin/stash.c
* builtin/upload-pack.c
* builtin/worktree.c
* bundle-uri.c
* push.c
* revision.c
* scalar.c
* builtin/patch-id.c
* t/helper/test-cache-tree.c
* t/helper/test-fast-rebase.c
* t/helper/test-reach.c
* t/helper/test-serve-v2.c
* t/helper/test-simple-ipc.c

l10n: po-id for 2.39 (round 1)

---

po/id.po

* builtin/gc.c
* builtin/interpret-trailers.c
* builtin/merge-file.c
* builtin/show-ref.c
* builtin/update-index.c
* chunk-format.c
* parse-options.c
* scalar.c
While at it, drop unused strings.

l10n: po-id for 2.43 (round 1)

---

.github/workflows/l10n.yml

This avoids the "Node.js 16 Actions are deprecated" warnings.
Since this workflow only runs in the l10n forks of `git/git`, it would be inappropriate to submit this patch to the Git mailing list for review, and I deem this the correct place to offer my contribution.

ci(l10n): bump Actions versions to avoid Node.js 16 deprecation warnings

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5579t)

---

po/zh_CN.po

l10n: zh_CN: for git 2.45 rounds

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5652t)

---

po/fr.po

l10n: fr: v2.46.0

---

po/sv.po

This pull request fixes the wrong "Signed-off-by" signature in pull request #784 . @nafmo 
Difference between c1a1a787b6 and c28545a6e2.
```
$ git range-diff c1a1a787b6~..c1a1a787b6 c28545a6e2~..c28545a6e2
1:  c1a1a787b6 ! 1:  c28545a6e2 l10n: sv.po: Update Swedish translation
@@ Metadata
l10n: sv.po: Update Swedish translation
-    Signed-Off-by: Peter Krefting <peter@softwolves.pp.se>
+    Signed-off-by: Peter Krefting <peter@softwolves.pp.se>
@@
```

l10n: sv.po: Update Swedish translation

---

po/id.po

* add-patch.c
* apply.c
* builtin/check-mailmap.c
* builtin/checkout.c
* builtin/gc.c
* builtin/multi-pack-index.c
* builtin/refs.c
* builtin/show-refs.c
* loose.c
* midx-write.c
* midx.c
* object-file.c
* ref-filter.c
* refs/file-backend.c
* scalar.c
* setup.c
* git-send-email.perl
* t/unit-tests/unit-tests.c

l10n: po-id for 2.47

---

po/zh_CN.po

l10n: zh_CN: updated translation for 2.47

---

po/bg.po

l10n: bg.po: Updated Bulgarian translation (5831t)

---

po/zh_TW.po

l10n: zh_TW: Git 2.49.0 round 1
